### ISSUE TITLE
[BUG] [2.1.0-beta.1] Feature(Features.RECORDING) gives a wrong initial value

### ISSUE THREAD

**Issue by PineapplePie** [Azure/azure-sdk-for-android#1058]
**Describe the bug**
If we are connecting to a meeting, which is already being recorded, we are getting a false value from Feature.RECORDING. 
I've checked with a small delay (1500L), it gives the same result. All other usages with using a recording listener work fine and as expected.

**To Reproduce**
1) Start a meeting
2) Start recording
3) Connect to the meeting, wait for the "Connected" status
4) Ping initial values from the library to check if the recording has been started. It should be true, but, in reality, it returns false. 

***Code Snippet***
val isRecording = call.feature(Features.RECORDING).isRecordingActive

**Expected behavior**
I would expect a correct boolean value. 

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Android
 - IDE : Android Studio Bumblebee
 - com.azure.android:azure-communication-calling:2.1.0-beta.1

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Hi @jsaurezlee-msft, would you mind taking a look? Thanks!
