### ISSUE TITLE
[BUG] CommunicationCalling hangUp metohds sometime takes longer to process

### ISSUE THREAD

**Issue by rahatur** [Azure/azure-sdk-for-android#1091]
**Describe the bug**
When a user is leaving communication channel (not even immediately joining the channel) then at times the `call?.hangUp` method takes way longer (e.g. over 15 seconds).

**To Reproduce**
Use Android SDK version 2.0.0 or above.
This problem does not exist lower version than 2.0.0 of the Android SDK with the same code base and Azure communication Service.

***Android Code Snippet***
```
suspend fun cleanAzureCall() = mutex.withLock{
        withContext(roomCoroutineScope.coroutineContext){
            call?.hangUp(HangUpOptions())?.join()
            call = null
            callAgent?.dispose()
            callAgent = null
        }
    }
```

**Expected behavior**
The Azure call object should be disposed off immediately without any crash or hang

**Setup (please complete the following information):**
 - OS: Android 8 and above 
 - IDE : Android Studio
 - SDK version 2.0.0 and above

**Comment by vcolin7** [comment]
Hi @rahatur, thanks for opening this issue, I'll pass it along to the right people. Could you take a look @jsaurezlee-msft? Thanks :)
