### ISSUE TITLE
[BUG] Android SDK - At times joins different meetings

### ISSUE THREAD

**Issue by rahatur** [Azure/azure-sdk-for-android#1092]
When users join a meeting with the same meeting ID sometimes it seems that they are in two different room. No one can see each other or hear each other. The user count in the room is 1 (suppose to be more than 1). But when a user leaves the room and joins again (with the same meeting ID) then they both can see each other.

**To Reproduce**
Two users join meeting room at the same time.

**Expected behavior**
They should be able to talk to each other and be on the same channel.

**Setup (please complete the following information):**
 - OS: Android 8 or above
 - IDE : Android Studio
 - 1.2.0, 2.0.0, 2.0.0-beta.1

**Comment by vcolin7** [comment]
Hi @rahatur, thank you for bringing this to our attention. Could you take a look @jsaurezlee-msft? Thanks :)

**Comment by RajithaE-jan** [comment]
@rahatur 
Hi is this teems meeting or group call?
For me, group calls are created as separate calls when using the same join id?

**Comment by rahatur** [comment]
Note: We have noticed that the issue seems to be occurring more on unstable connections and when device switches between wifi and mobile data (even when both are stable).
