### ISSUE TITLE
[BUG] Regression: Raw media access stop working after some time

### ISSUE THREAD

**Issue by paolo-ermit** [Azure/azure-sdk-for-android#1100]
**Describe the bug**
Stream sent using a raw media access (https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access) stop working after a few minutes (it depends).
The problem is present in library com.azure.android:azure-communication-calling version 2.1.0-beta.1
The problem was not present in version 2.0.0-beta.1

***Exception or Stack Trace***
No error nor trace is available.
Function SoftwareBasedVideoFrame.SendFrame(...) keeps returning a valid FrameConfirmation object with status=0, as it does when the frame is sent

**To Reproduce**
Run provided sample (https://github.com/Azure-Samples/communication-services-android-quickstarts/tree/main/RawMediaAccess) with 2.1.0-beta.1

***Code Snippet***
n/a

**Expected behavior**
Video stream should be sent without interrupting

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Android
 - IDE : Android Studio
 - Version of the Library used: com.azure.android:azure-communication-calling;2.1.0-beta.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Hi @paolo-ermit, thanks for bringing this to our attention. Would you mind taking a look @gaobob-msft @jsaurezlee-msft?

**Comment by paolo-ermit** [comment]
In version 2.3.0-beta.1 (with the redesigned api) it's working correctly
