### ISSUE TITLE
[FEATURE REQ] Get Info about Raw media access accepted resolutions

### ISSUE THREAD

**Issue by paolo-ermit** [Azure/azure-sdk-for-android#1101]
**Is your feature request related to a problem? Please describe.**
This is related to com.azure.android:azure-communication-calling
When using the Raw media access (https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access) it is possible to specify the resolution of the video.
But it seems that only some sizes are supported (right now I found 640x480, 1920x1080, 1280x720).
When using a un-supported resolution, there is no error, and the only way to know that the video is not being transmitted it so look at the received stream.

**Describe the solution you'd like**
I would like to have a list of supported resolutions in the documentation, and a way to know that the selected resolution is not accepted (it could be an exception when creating a VideoFormat object, on an errore when calling OutboundVirtualVideoDeviceOptions.setVideoFormats(...)

**Describe alternatives you've considered**
The only workaround I have is to try to manually get a list of the supported resolutions by retrials, and then to filter the resolutions at run time

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [ x] Expected solution specified

**Comment by vcolin7** [comment]
Hi @paolo-ermit, thanks a lot for the feedback, I'll make sure to pass it along to the team :)

**Comment by SaadAhmed1122** [comment]
Getting same bug when changing the resolution of the video is not transmitting.

**Comment by yassirbisteni** [comment]
@paolo-ermit we already have documentation for the supported resolutions, you can check this link: https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access?pivots=platform-windows

**Comment by yassirbisteni** [comment]
@paolo-ermit we already have documentation for the supported resolutions, you can check this link: https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access?pivots=platform-windows

**Comment by vcolin7** [comment]
@SaadAhmed1122 I think what the original issue meant to say is that if you try to use an unsupported resolution then there was no way to know if the video was being transmitted. If you found a different issue that arises when changing the video resolution, would you mind [reporting it as a bug](https://github.com/Azure/azure-sdk-for-android/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=%5BBUG%5D)?

**Comment by SaadAhmed1122** [comment]
@vcolin7  @yassirbisteni  I wanted to add the zoom feature in my local stream video when my local sent to the other participant It should sent with that zoom or resolution.

**Comment by gaobob-msft** [comment]
@SaadAhmed1122 are you looking to change the resolution on the outgoing video stream or the incoming video stream

**Comment by SaadAhmed1122** [comment]
Outgoing video stream
