### ISSUE TITLE
[BUG] Users do not hear each other during a call.

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Azure/azure-sdk-for-android#1108]
**Describe the bug**

It seems to me that there are problems only for ***android 12*** users, the microphone seems to be muted and the other end does not listen, when the user changes the audio output it is possible to hear his voice but then it slowly disappears until nothing is heard.

We are using the official example of the repository to test and the problem occurs in the same.

https://github.com/Azure-Samples/communication-services-android-calling-hero
***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

Participants: user1(Android 12), user 2(Android 11), user3(Android 11)
Problematic scenario: user1 with user2

Scenario where it works: user2 and user3

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Android]
 - IDE : [e.g. Android Studio]
 - Version of the Library used (com.azure.android:azure-communication-calling; 2.0.0 or 2.1.0-beta.1)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by vcolin7** [comment]
Hi @andersonvieiragomeslopes, thanks for reporting this, I'll pass it along to the team.
@jsaurezlee-msft could you take a look? :)
