### ISSUE TITLE
[BUG] Raw media access not available in azure-communication-calling version 2.3.0-beta.1

### ISSUE THREAD

**Issue by paolo-ermit** [Azure/azure-sdk-for-android#1125]
**Describe the bug**
azure-communication-calling:2.3.0-beta.1 does not contain RAW media features
RAW media functions have been available since now in beta versions, as a preview feature

***Exception or Stack Trace***
n/a

**To Reproduce**
Update the library to azure-communication-calling:2.3.0-beta.1

***Code Snippet***
n/a

**Expected behavior**
Having raw media functions available in the beta version

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Android
 - IDE : Android Studio
 - Version of the Library used: azure-communication-calling:2.3.0-beta.1

**Additional context**
I understand that RAW media access feature is in Public Preview, so there is no guarantee that it will be kept.
I would like to know if this feature is not present temporarily or if it is going to be removed. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [ x] Repro Steps Added
- [x ] Setup information Added

**Comment by jsaurezlee-msft** [comment]
Hi @paolo-ermit thanks for the report. @viniciusl-msft can you take a look why Raw media access might not be present in 2.3.0-beta.1?

**Comment by viniciusl-msft** [comment]
Hi @paolo-ermit, thanks for the report and sorry for the trouble.

This version has some breaking changes on the Raw Media Support but it is still available. I'm updating the release notes to make explicit the changes. We are updating the Quickstarts to reflect the new usage as well, I'll let you know when it is available.. Meanwhile, I suggest to keep the previous version while you familiarize with the changes needed to keep the functionality as is.

**Comment by viniciusl-msft** [comment]
Release Notes Updated: https://github.com/Azure/Communication/blob/master/releasenotes/acs-calling-android-sdk-release-notes.md

**Comment by paolo-ermit** [comment]
Great, it works :)
I think this one is resolved
