### ISSUE TITLE
[BUG] Low volume during the call on all versions except for 1.2.0-beta.2

### ISSUE THREAD

**Issue by PineapplePie** [Azure/azure-sdk-for-android#1134]
**Describe the bug**
We're facing the situation when the volume is really low during our calls. It seems like a similar issue which was described here: https://github.com/Azure/azure-sdk-for-android/issues/1108, but it occurs on all Android versions and it's not limited by the latest Android 12. We've tried to include different system Android volume flags and checked the Calling Hero sample implementation, but it didn't help and it looks like the issue is hidden inside the library. We examined every version of the library and the only one which hasn't got this problem is 1.2.0-beta.2, so we have to downgrade :(

***Exception or Stack Trace***
n/a

**To Reproduce**
1. Connect to a meeting
2. Move your head more than 10-20 cm away from the mic of the device or turn it halfway (90 degrees) and try to say something
3. The participant on the other side won't hear you at all. Sometimes it seems that the sound has completely disappeared or it's so low that you can't hear it.

Then you can change the version of the lib to 1.2.0-beta.2 in your dependency file and compare the "volume results".

***Code Snippet***
n/a

**Expected behavior**
Volume should be louder. It would be also awesome to have it as a configurable setting on the client side! 

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Android 9-12 (checked on a variety of devices)
 - IDE : Android Studio
 - Version of the Library used: 2.0.0, 2.1.0-beta.1, also tried to use 2.3.0-beta.1. Neither of them worked, the only option is 1.2.0-beta.2 so far

**Additional context**
n/a 
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Hi @PineapplePie, thanks for reporting this, I'll pass it along to the team. Could you take a look @jsaurezlee-msft, @gaobob-msft?

**Comment by PineapplePie** [comment]
@jsaurezlee-msft, @gaobob-msft Any updates on this issue?
