### ISSUE TITLE
[BUG] [AzureCommunicationCalling] Local video render seems stuck in portrait mode

### ISSUE THREAD

**Issue by tompi** [Azure/azure-sdk-for-android#1153]
**Describe the bug**
On some android devices, the camera does not respect the orientation of the app(when in landscape), and just shows a  stretched portrait image. This is SEMI consistent, I have at least one test phone, huawei, where this USUALLY happens, but NOT always...

**To Reproduce**
Steps to reproduce the behavior: start the app with the device oriented in landscape.
Goto a page with a LocalVideoStream, and check the preview.

***Code Snippet***
                var camera = _deviceManager.Cameras.First(c => c.CameraFacing == _cameraFacing);
                _localVideoStream = new LocalVideoStream(camera, MainActivity.Instance);
                _localVideoRenderer = new VideoStreamRenderer(_localVideoStream, MainActivity.Instance);
                var renderingOptions = new CreateViewOptions(ScalingMode.Fit);
                var nativeView = _localVideoRenderer.CreateView(renderingOptions);

**Expected behavior**
Camera renderer should show regular landscape preview.

**Screenshots**
Working ok on an old samsung galaxy s7, android 8
![IMG_1845](https://user-images.githubusercontent.com/231717/177941899-2783c559-1300-42af-8253-2336295744cb.jpg)

Not looking good on a samsung galaxy tablet s6, android 11. Image is stretched, so MIGHT be landscape just rotated?
![IMG_1846](https://user-images.githubusercontent.com/231717/177941964-8b3dd90a-bdd5-42b8-af5e-15b0372f6e86.jpg)

**Setup (please complete the following information):**
 - OS: Android 8 and 11, probably a lot more, have seen it on a lot of phones
 - IDE : Rider
 - Version of the Library used: 2.3.0-beta.1

**Comment by vcolin7** [comment]
Hi @tompi, thanks for reporting this, I will pass it along to the team.

//cc @jsaurezlee-msft @gaobob-msft

**Comment by jsaurezlee-msft** [comment]
Hi @tompi thanks for the report. When you have this scenario and you are in a call with other participants, those participants see the video sideways and stretched also? I'm trying to see if this is something that happens only in the preview video of the phone, or if it's also affecting the way other participants see your video.

**Comment by tompi** [comment]
@jsaurezlee-msft sorry about the late reply, this happens only in local preview. Just tested on galaxy s8, still happening. 

Not sure if this applies to previous versions of sdk.

This is probably related to the way Im managing orientation, my start page is portrait only, when I go to the page with video, I flip orientation to landscape only, probably this that creates a problem on some phones/tablets. Do you need a minimal repro app maybe?

**Comment by gaobob-msft** [comment]
@tompi can you please do a quick check and see if the following listener is being triggered when you from portrait only to landscape only? https://developer.android.com/reference/android/view/OrientationEventListener

**Comment by gaobob-msft** [comment]
@rbuiten what version of the SDK are you using? CC: @yassirbisteni

**Comment by rbuiten** [comment]
currently we are on 2.2.2, but we will go to the latest stable within a few weeks.
