### ISSUE TITLE
Empty strings in ID are not allowed

### ISSUE THREAD

**Issue by passeride** [Azure/azure-sdk-for-android#116]
### Environment

- Android version: 9
- Azure.Android SDK: current
- Azure.Android SDK version: current

### Bug Summary
When trying to create a document with the ID set as empty string it does not allow.

Error says something about white space not being allowed. 

### Steps to Reproduce
Upload 

### Code snippet

```kotlin
// TODO: add code here (if applicable)
             var person = ApiPerson(id: "", name:"name")
            AzureData.createOrReplaceDocument(person, USER_COLLECTION, DATABASE_ID) {
// SUCCESS
            }

```

### Expected Behavior
Empty ID will make the COSMODB create an ID for the object

### Actual Behavior
Network reqeust is not executed and error says that white space is not allowed

**Comment by NateRickard** [comment]
The original intent was that you assign an Id to your Document before calling `createOrReplaceDocument` OR leave the Id alone (null) and [let it generate a random Id for you](https://github.com/Azure/azure-sdk-for-android/blob/218a8e550bc0d0ec5546235518ee3a7b121ade55/azuredata/src/main/java/com/azure/data/model/Resource.kt#L20).

**Comment by passeride** [comment]
Forgot to update this one.. I copied the string from the README and used an older version #117 
The newer version did behave better, but the potential error is still vague tho. 

Sorry for late update. Thanks for looking into it
