### ISSUE TITLE
Version in readme is outdated

### ISSUE THREAD

**Issue by passeride** [Azure/azure-sdk-for-android#117]
Just a heads up... cost me some time now..

The version in install section says to use 

compile 'com.azure.android:azuredata:0.1.0'

but we are on version 0.4.0 now... would be nice if this could be updated.

**Comment by NateRickard** [comment]
it gives that as an example... the next sentence says: 

>The correct Gradle package specifier can be found by navigating to the package or clicking the above "Download" button for the SDK. Then view the Maven/Gradle information and copy the Gradle snippet into your Gradle file.

I can update the example, but it will likely be outdated again since it's not an automatically updated value. Agreed that this part of the doc is a bit clumsy, and this will likely change in the future.
