### ISSUE TITLE
Does azure-communication-calling android sdk support external cameras?

### ISSUE THREAD

**Issue by haohighview** [Azure/azure-sdk-for-android#1174]
Does azure-communication-calling android sdk support external cameras?

**Comment by vcolin7** [comment]
Hi @haohighview, thanks for your interest in using Azure Communication Calling, I have forwarded your question to the team :)

/cc @jsaurezlee-msft, @gaobob-msft

**Comment by jsaurezlee-msft** [comment]
Hi @haohighview, the Azure Communication SDK for Android currently does not support external cameras.

On BETA SDKs like 2.3.0-beta.1, we support Raw Media Access. So in this case, you can capture the video feed from the external camera in your application, and then use Raw Media Access to stream that video in a call.

Here's a quickstart for Raw Media Access.
[Quickstart - Add RAW media access to your app - An Azure Communication Services quickstart | Microsoft Docs](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access?pivots=platform-android)

I'm closing this issue as this feature is not support in the SDK.
