### ISSUE TITLE
[BUG] Azure core retry policy

### ISSUE THREAD

**Issue by jiminwen-msft** [Azure/azure-sdk-for-android#1176]
**Describe the bug**
Parent task with context: [Task 2934101: [Android] requesting send message with no network, return no status code - Boards (visualstudio.com)](https://skype.visualstudio.com/SPOOL/_workitems/edit/2934101). I think the retry-policy library provided by azure-core needs to add checking for null response. Our clients are seeing NPE when the network is closed/poor. The reason is that there is no response in this situation, but retry-policy class still tries to get status code: [azure-sdk-for-android/RetryPolicy.java at bd9aeea4b47c945943ca918c63a2d49015f66057 · Azure/azure-sdk-for-android (github.com)](https://github.com/Azure/azure-sdk-for-android/blob/bd9aeea4b47c945943ca918c63a2d49015f66057/sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/RetryPolicy.java#L169). 

***Exception or Stack Trace***
com.azure.android.core.http.policy.RetryPolicy.calculateRetryDelay(RetryPolicy.java:169)
com.azure.android.core.http.policy.RetryPolicy.retryIfRequired(RetryPolicy.java:129)
com.azure.android.core.http.policy.RetryPolicy.access$000(RetryPolicy.java:23)
com.azure.android.core.http.policy.RetryPolicy$1.onError(RetryPolicy.java:92)
com.azure.android.core.http.HttpPipelinePolicyChainImpl.completedError(HttpPipelinePolicyChainImpl.java:202)
com.azure.android.core.http.PolicyCompleter.completedError(PolicyCompleter.java:53)
com.azure.android.core.http.policy.CookiePolicy$1.onError(CookiePolicy.java:81)
com.azure.android.core.http.policy.CookiePolicy$1.onError(CookiePolicy.java:81)
com.azure.android.core.http.HttpPipelinePolicyChainImpl.completedError(HttpPipelinePolicyChainImpl.java:202)
com.azure.android.core.http.HttpPipelinePolicyChainImpl.completedError(HttpPipelinePolicyChainImpl.java:208)
com.azure.android.core.http.PolicyCompleter.completedError(PolicyCompleter.java:53)
com.azure.android.core.http.policy.HttpLoggingPolicy$1.onError(HttpLoggingPolicy.java:202)
...(Skipping a few lines)
...
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
java.lang.Thread.run(Thread.java:1012)

**To Reproduce**
Using chat SDK sample APP: 
1. Close the network
2. Run chat sample APP
3. Send new message using the APP

***Code Snippet***
https://github.com/Azure/azure-sdk-for-android/blob/bd9aeea4b47c945943ca918c63a2d49015f66057/sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/RetryPolicy.java#L169

**Expected behavior**
NPE being thrown

**Screenshots**

**Setup (please complete the following information):**
 - OS: Android
 - IDE : Android Studio
 - Version of the Library used: azureCoreVersion = "1.0.0-beta.10"

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y ] Bug Description Added
- [Y ] Repro Steps Added
- [Y] Setup information Added

**Comment by vcolin7** [comment]
Hi @jiminwen-msft, I'm looking into this and should have a fix soon.
