### ISSUE TITLE
Add support for joining Rooms.

### ISSUE THREAD

**Issue by chaosifier** [Azure/azure-sdk-for-android#1198]
It would be great if we could join rooms through the SDK.

[Rooms Quickstart](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/rooms/join-rooms-call?pivots=platform-android)

**Comment by gaobob-msft** [comment]
@radubulboaca can help answer.

**Comment by andersonvieiragomeslopes** [comment]
Hello, @chaosifier

I just checked and this feature is available in version 2.4.0-beta.1 just update and make use of the feature.
