### ISSUE TITLE
Create azure-identity binding to MSAL

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#120]
Create an identity library that makes it easy to use MSAL for Android with the HTTP pipeline in Core.

- [x] Define OAuth2 (bearer token) interface in Core
- [ ] Come up with public API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests

**Comment by vcolin7** [comment]
Stories we can break this Epic into on a high level:

- [ ] Determine if we'll make use of the MSAL library and, if so, how much of that will be required.
- [ ] Define which types of authentication are part of the scope for this effort. Tentatively:
    - OAuth2 (bearer token)
    - SAS Token
- [ ] Come up with public sync API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests

**Comment by bsiegel** [comment]
Updated the description, thanks!

**Comment by baywet** [comment]
Hey team,
I'm from the MS Graph SDK team, working on the java/android experience right now.
We have [ongoing work](https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42) to take a dependency on azure-identity and simplify the auth story for our SDK.
If the package is available for java and works well, it has an android API level requirement of 26 and higher. Which is probably too high for our audience.

I'm reaching out to understand what are the timelines for an android version? what will be the minSdkVersion (API level) for it? and do you have any other information you can share? Thanks!
