### ISSUE TITLE
[BUG] Duplicate ACCESS_NETWORK_STATE permission

### ISSUE THREAD

**Issue by jomar-olaybal** [Azure/azure-sdk-for-android#1206]
**Describe the bug**
azure-communication-chat Android Manifest has duplicate ACCESS_NETWORK_STATE permission

***Exception or Stack Trace***
[com.azure.android:azure-communication-chat:2.0.0] /Users/jom/.gradle/caches/transforms-3/c17b1c709fb41ccbb3f9de6f191d883f/transformed/jetified-azure-communication-chat-2.0.0/AndroidManifest.xml:19:5-79 Warning:
	Element uses-permission#android.permission.ACCESS_NETWORK_STATE at [com.azure.android:azure-communication-chat:2.0.0] AndroidManifest.xml:19:5-79 duplicated with element declared at [com.azure.android:azure-communication-chat:2.0.0] AndroidManifest.xml:18:5-79

**Comment by vcolin7** [comment]
Hi @jomar-olaybal, thanks for reporting this. I will route it to the team :)

**Comment by vcolin7** [comment]
@jiminwen-msft would you mind taking a look when you get a chance?
