### ISSUE TITLE
Azure Cosmosdb CreateDocument : Partitionkey does not match with header

### ISSUE THREAD

**Issue by ronaksatva** [Azure/azure-sdk-for-android#123]
### Environment

- Android version: 28
- Azure.Android SDK: Azure Data
- Azure.Android SDK version: 0.3.0

### Bug Summary
**Exact Error :** 
Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]}

I got the partitionkey does not match with the header. But i didn't create the cosmosdb with required partitionkey. For my ios app the sdk is working fine and able to create the document but for the Android app i got this error and i did match my code with the ios code both are almost same.

### Steps to Reproduce
Use createDocument function

### Code snippet

 AzureData.createDocument(dataResponse, "XXXXXX", "XXXXXXX", "", "", "[]", onCallback(o -> {

                }));

Note : i did something same in IOS app and its working fine i got this issues in android integration.

**Comment by NateRickard** [comment]
[Creating containers without partition keys is deprecated](https://stackoverflow.com/questions/55224670/cosmosdb-container-without-partitionkey), and this library removed the ability to work with partition key-less containers accordingly.
