### ISSUE TITLE
Implement basic HTTP Pipeline with OkHttp + Retrofit

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#132]
Port our existing pipeline architecture to Android using OkHttp and Retrofit. This should include the proper hook points for customer-provided Interceptors.

**Comment by anuchandy** [comment]
We follow existing OkHttp interceptor based pipeline architecture. 

a a type `ServiceClient` #157 is added to simplify sharing of http resources +Retrofit instance,  which supports adding custom okhttp interceptors and allows replacing subset of interceptors such as credential interceptor.
