### ISSUE TITLE
Implement configuration for HTTP Pipeline

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#145]
Support global configuration of pipeline policies:
- [x] Logging: log level, logger implementation
- [ ] Global configuration hierarchy #314
- [ ] TelemetryOptions #315
- [ ] TransportOptions (Retry/Timeout) #316
- [ ] ~Load / store configuration~

**Comment by vcolin7** [comment]
Telemetry is supported but cannot be disabled at the moment.

**Comment by vcolin7** [comment]
What I said earlier is incorrect: telemetry is supported via adding a UserAgentInterceptor to an HTTP pipeline, if said interceptor is not added, then telemetry won't be enabled for a given pipeline.

**Comment by bsiegel** [comment]
Closing in favor of child tasks
