### ISSUE TITLE
Add CheckStyle, Spotbugs, and JavaDoc to build

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-android#168]
We should bring over the configurations that make sense from the Java repo

- [x] Checkstyle (using rules from Java repo, minus the custom rules (for now))
- [x] SpotBugs (using the rules from the Java repo)
- [x] JavaDoc (configured to exclude `implementation` packages, as decided)
- [x] All linting, compiler, doc configurations set to fail on error and fail on warning

**Comment by anuchandy** [comment]
@vcolin7 would you be able to investigate and help here?

**Comment by kurtzeborn** [comment]
Labeling this "Client" as the mobile libraries team should own this work.  Please reach out to the EngSys team for direction if needed and for code review of the changes to add these to ensure consistency with how it's done in other langauges/repos.

**Comment by anuchandy** [comment]
I've the quality checks integrated for as part of vnext Android azure core modules work in progress, hopefully the modules will land in the official repo soon.

**Comment by anuchandy** [comment]
The branch [v2-sdk](https://github.com/Azure/azure-sdk-for-android/tree/feature/v2-sdk) (containing the WIP azure core modules) is pushed, contains the code quality checks which can be invoked by running `gradle check`.

**Comment by anuchandy** [comment]
Implemented in v2-sdk branch and CI now runs all the quality tool listed in the work item description.
