### ISSUE TITLE
Increase code coverage of unit tests for Preview 1

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#189]
We need to write more unit tests in order to hit code coverage targets for:
- [x] azure-core
- [ ] ~~azure-identity~~
- [x] azure-storage-blob

The code coverage target is 70% for each framework.

**Comment by vcolin7** [comment]
Azure Core local unit test coverage is currently sitting at 80% classes and 70% lines where applicable.

Azure Storage local unit test coverage is currently sitting at 91% classes and 69% lines where applicable.
