### ISSUE TITLE
TransferManager must handle block / blob uploads

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#196]

**Comment by vcolin7** [comment]
TransferManager handles single block blob uploads for the moment. Aggregate uploads (multi-file) pending.

**Comment by anuchandy** [comment]
I believe this feature (multi-upload/download) is not in the preview-1 list anymore. Based on my chat with @tjprescott @bsiegel design/experience is yet to discuss and user study didn't include this scenario.

**Comment by tjprescott** [comment]
@anuchandy correct. Not necessary for preview 1
