### ISSUE TITLE
[Question] The default network type for Transfer Manager 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-android#213]
Should transfer manager default to any specific network type if not specified or should it throw? 

Reference: https://github.com/Azure/azure-sdk-for-android/pull/203#discussion_r387957472

**Comment by anuchandy** [comment]
\\cc @tjprescott, It will be good to be consistent with this behavior.

**Comment by anuchandy** [comment]
@adrianhall FYI - we use `NetworkType.CONNECTED` as the default for android. i.e. default to any network connection, which seems okay, if you think otherwise, please let's know.

**Comment by adrianhall** [comment]
Nope - that's preferred.  The developer can make the choice then, and it works out of the box.

**Comment by anuchandy** [comment]
@adrianhall sounds good, closing this issue.
