### ISSUE TITLE
AzureData: Suspend function

### ISSUE THREAD

**Issue by Raysapps** [Azure/azure-sdk-for-android#240]
### Question
Are there any plans to support  "suspend function API"?
 I would like to delegate the AzureData.getDocument() API call as background  task to the WorkManager and save the retrieved data into the  Room database. If there is a suspend AzureData.getDocument() API returning the output then it will be helpful to avoid the callback passed to the API.

**Comment by bsiegel** [comment]
Closing this issue as we aren't planning any further changes to the Track 1 SDK.
