### ISSUE TITLE
Beta JavaDoc link in use in README.md

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-android#284]
Android JavaDoc has not published yet, so verify links will treat it as broken links. Put the link under ignore-links to skip the check temporarily. Please remember to remove it after JavaDoc link gets published.

**Comment by sima-zhu** [comment]
The links have been updated to beta one. Not an issue from readme perspective. Feel free to close it if it is not that important.

**Comment by bsiegel** [comment]
Currently the javadoc on github.io is versioned - we will either not version the javadoc going forward, or we will need to automate changes to the index page.

**Comment by sima-zhu** [comment]
Close the issue as it is not in the scope
