### ISSUE TITLE
Use TelemetryOptions in UserAgentInterceptor

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#315]
Based on the provided TelemetryOptions, configure the UserAgentInterceptor to use the provided application ID, and to include or exclude identifying information. See the implementation in https://github.com/Azure/azure-sdk-for-ios/commit/c45005ff85f27cb6695357d5a0d1bceca83af59d

**Comment by vcolin7** [comment]
This was fixed by #345.
