### ISSUE TITLE
Create Auto Release Notes Script

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-android#354]
Take this .NET script that Pavel created and adapt it to Android

https://github.com/Azure/azure-sdk-for-net/blob/master/eng/scripts/Collect-Changelogs.ps1

**Comment by joshfree** [comment]
Related - https://github.com/Azure/azure-sdk-for-java/issues/15374

**Comment by weshaggard** [comment]
Tracking the general work with Azure/azure-sdk#1694
