### ISSUE TITLE
Onboard android github io docs to eng/common automation process

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-android#487]
Android currently manually updates the github IO pages. 
https://azure.github.io/azure-sdk-for-android/

Other lang repos (Java, .NET, Python, Js, C, CPP) have already unified the look of the landing page. It is better to have Android to align with other SDK lang repos and automate the process.

Use the issue to track the future work.

**Comment by kurtzeborn** [comment]
I've closed the duplicate issue.  Copying over this comment from that issue:

> Assigning this back to the client team for follow up. The infrastructure is all in place for how and where to publish these. We've done a lot of work to make the toolset and look and feel of our github.io docs across repos. Once you have docs generating using the appropriate refdoc generation tools for our mobile languages, please work with @danieljurek Daniel Jurek FTE to plug it into our systems and get them published.
