### ISSUE TITLE
Create plan / prototype for modularizing azure-core

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#489]
In this pass, we want to extract out our large 3rd party dependencies (HTTP client & serializer) into modules that can be replaced by the end developer if they wish to use different libraries to provide that functionality.

**Comment by anuchandy** [comment]
Work items tracking the progress:

HttpClient + Pipeline: https://github.com/Azure/azure-sdk-for-android/issues/529
HttpClient impls: https://github.com/Azure/azure-sdk-for-android/issues/530
HttpCall dispatcher: https://github.com/Azure/azure-sdk-for-android/issues/531
Serde: https://github.com/Azure/azure-sdk-for-android/issues/528

**Comment by anuchandy** [comment]
Implemented in v2-sdk branch (hosting new azure core modules) and ACS chat SDK is using the new design.
