### ISSUE TITLE
Add support for server-provided Retry-After value

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#497]
Retry-After header is not used. When this header is returned, client is expected to retry with delays.

Either make a new RetryStrategy (e.g. RetryAfterStrategy) that uses this value, or perhaps it makes more sense to make this a configurable setting on either an existing retry strategy or on the retry interceptor itself. My intuition says that the former makes more sense, but I'm open to being convinced otherwise.

**Comment by anuchandy** [comment]
[implemented](https://github.com/Azure/azure-sdk-for-android/blob/2714bf7d4e6262d455757f48758c890bea533415/sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/RetryPolicy.java#L182) in v2-sdk branch (where new azure core modules are hosted).
