### ISSUE TITLE
[Autorest.Android] The Android CodeGen for the new azure core module system

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-android#651]
In Impl level:
- [x] Override to add .android in the namespace.
- [x] Override the following part of "RestProxy":
- [x] Enable multiple ExceptedResponse annotations
- [x] Change return type from reactor type to void
- [x] Add callback parameter as the last argument.

In public methods:
- [x] Changing return type from Reactor type to CompletableFuture
- [x] Filter out PagedFlux|PagedIterable methods (i.e., don't produce them)
- [x] Method body to convert callback in RestProxy to CompletableFuture.

**Comment by JianpingChen** [comment]
https://github.com/Azure/autorest.java/pull/967
