### ISSUE TITLE
First release of new azure core modules [ETA: March-18]

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-android#657]
Ensure the "first" release of all azure core modules happens by 03/18

The modules to release are under - https://github.com/Azure/azure-sdk-for-android/tree/feature/v2-sdk-acs/sdk/core
The plan is to have a couple of core beta releases before RCing Chat SDK; that way, we get enough time to identify and address any hidden issues.

**Comment by vcolin7** [comment]
The release was completed successfully:
- [azure-core](https://search.maven.org/artifact/com.azure.android/azure-core/1.0.0-beta.4/aar)
- [azure-core-credential](https://search.maven.org/artifact/com.azure.android/azure-core-credential/1.0.0-beta.4/aar)
- [azure-core-http](https://search.maven.org/artifact/com.azure.android/azure-core-http/1.0.0-beta.4/aar)
- [azure-core-http-httpurlconnection](https://search.maven.org/artifact/com.azure.android/azure-core-http-httpurlconnection/1.0.0-beta.4/aar)
- [azure-core-http-okhttp](https://search.maven.org/artifact/com.azure.android/azure-core-http-okhttp/1.0.0-beta.4/aar)
- [azure-core-jackson](https://search.maven.org/artifact/com.azure.android/azure-core-jackson/1.0.0-beta.4/aar)
- [azure-core-logging](https://search.maven.org/artifact/com.azure.android/azure-core-logging/1.0.0-beta.4/aar)
- [azure-core-rest](https://search.maven.org/artifact/com.azure.android/azure-core-rest/1.0.0-beta.4/aar)
- [azure-core-test](https://search.maven.org/artifact/com.azure.android/azure-core-test/1.0.0-beta.4/aar)
