### ISSUE TITLE
Broken link in Communication README

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-android#719]
For an unrelated PR, link checker found a broken link:

```none
Found 22 links on page file:///mnt/vss/_work/1/s/sdk/communication/azure-communication-common/README.md
##[warning][404] broken link https://azure.github.io/azure-sdk-for-android/sdk/communication/azure-communication-common/azure-communication-common/index.html
```

**Comment by vcolin7** [comment]
Please refer to [this comment](https://github.com/Azure/azure-sdk-for-android/pull/720#discussion_r605878365) for more information about the cause.

**Comment by heaths** [comment]
Would it make sense to track it with this issue then? Or is there another one already?

**Comment by vcolin7** [comment]
There's no issue tracking this, so let's use this one.
