### ISSUE TITLE
After recovering from offline mode, local cache never got updated from changes on cloud

### ISSUE THREAD

**Issue by wikes82** [Azure/azure-sdk-for-android#77]
## Bug Information
After recovering from offline mode, Android local cache never get updated from new changes (create/update/delete) from the cloud. 

### Steps to Reproduce
Go offline, make some changes on the cosmos db cloud (create/update or delete). Turn back internet access on the Android. You will see Android local cache still has the old non updated data. Even if you restart the App, if you go back to offline mode, it will show you the old cached data.

### Expected Behavior
When Android recover internet connection, any changes from the cloud should be synced back to Android local cache after fetching new data (using : getDocuments, getDocument, queryDocuments,etc) from cloud.

**Comment by bsiegel** [comment]
Thanks for your report. We are preparing for a release of the Track 2 SDK libraries which are based on a different codebase than the current libraries. Since we're not planning for further releases of the existing libraries, we're not able to work on resolving this issue at the current time.
