### ISSUE TITLE
Change listener on client ?

### ISSUE THREAD

**Issue by SogoGolf** [Azure/azure-sdk-for-android#80]
This is not a bug but more of a feature request. Is it possible to have the Azure.Android (and iOS) API make use of "change listeners" so that if data changes on the CosmosDB server, that change(s) would automatically trigger the listener in the mobile client app ? (Same feature that Firebase, Realm have).

**Comment by bsiegel** [comment]
Thanks for your request. We are preparing for a release of the Track 2 SDK libraries which are based on a different codebase than the current libraries. Since we're not planning for further releases of the existing libraries, we're not able to work on implementing your request at the current time.

**Comment by SogoGolf** [comment]
Hi @bsiegel thanks for letting us know. Since we've built our now in production apps for ios and Android, based on the 'existing libraries' (which you note are not being worked on) what impact will this have on the Sogo Golf app?
