### ISSUE TITLE
[BUG] azure-sdk-for-android: A request was made to load the default HttpClient provider but one could not be found on the classpath.

### ISSUE THREAD

**Issue by Muqeeth-Pop** [Azure/azure-sdk-for-android#928]
**Describe the bug**
Following [https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-android](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-android) got the below error.

***Exception or Stack Trace***
java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-okhttp or azure-core-http-httpurlconnection. Depending on your existing dependencies, you have the choice of OkHttp or HttpUrlConnection implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.

**To Reproduce**
Follow the steps to run the example from [https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-android](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-android)

***Code Snippet***
Code snippet that causes the issue.
```
chatThreadAsyncClient = new ChatThreadClientBuilder()
        .endpoint(ResourceUrl)
        .credential(new CommunicationTokenCredential(UserToken))
        .chatThreadId(threadId)
        .buildAsyncClient();
```

**Expected behavior**
App should compile and run successfully. And should be able to send and receive messages in the teams meeting.

**Setup:**
 - OS: macOS Catalina Version 10.15.7
 - IDE : Android Studio Arctic Fox | 2020.3.1 Patch 1
 - Version of the Library used: 1.0.0 (com.azure.android:azure-communication-chat:1.0.0)

**Additional context**
We're trying to connect our custom app with the teams meeting. We're able to join the teams meeting, audio & video is working fine. However the chat SDK is throwing the above error.
As per the stack trace we tried to add the following libraries to classpath in build.gradle file, but the error still persists.
```
classpath("com.azure:azure-core-http-okhttp:1.6.1")
```

**Information Checklist**
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
It looks like the problem lies in that you are referencing a Java libray instead of the one written specifically for Android, the one you want is [this one](https://search.maven.org/artifact/com.azure.android/azure-core-http-okhttp/1.0.0-beta.9/aar): `
com.azure.android:azure-core-http-okhttp:1.0.0-beta.9`. We'll make sure that the error message is clearer so this doesn't happen again in the future.

Would you mind trying using the library I referenced above and letting me know if the problem persists? :)

**Comment by Muqeeth-Pop** [comment]
@vcolin7 I'm getting the same error if I add it in app level dependencies (app/build.gradle).
```
implementation "com.azure.android:azure-core-http-okhttp:1.0.0-beta.9"
```
_**Exception or Stack Trace**_

java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-okhttp or azure-core-http-httpurlconnection. Depending on your existing dependencies, you have the choice of OkHttp or HttpUrlConnection implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.

If I add it in project level dependencies (build.gradle) the following error occurred.
```
classpath("com.azure.android:azure-core-http-okhttp:1.0.0-beta.9")
```
_**Exception or Stack Trace**_
```
A problem occurred configuring root project 'AppName'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve com.azure.android:azure-core-http-okhttp:1.0.0-beta.9.
Required by:
project :
> No matching variant of com.azure.android:azure-core-http-okhttp:1.0.0-beta.9 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
- Variant 'releaseApiPublication' capability com.azure.android:azure-core-http-okhttp:1.0.0-beta.9 declares a library, and its dependencies declared externally:
- Incompatible because this component declares an API of a component, with the library elements 'aar' and the consumer needed a runtime of a component, packaged as a jar
- Other compatible attribute:
- Doesn't say anything about its target Java version (required compatibility with Java 8)
- Variant 'releaseRuntimePublication' capability com.azure.android:azure-core-http-okhttp:1.0.0-beta.9 declares a runtime of a library, and its dependencies declared externally:
- Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, packaged as a jar
- Other compatible attribute:
- Doesn't say anything about its target Java version (required compatibility with Java 8)
```

**Comment by vcolin7** [comment]
Would you mind sharing your app's `build.gradle` files or your dependency tree? You can get the latter by using `gradle app:dependencies` or `./gradlew app:dependencies`.

Are you using a custom proguard file as well?

**Comment by Muqeeth-Pop** [comment]
Please find the attached build.gradle files and dependency tree.

[dependencies.txt](https://github.com/Azure/azure-sdk-for-android/files/7513216/dependencies.txt)
[build.gradle.txt](https://github.com/Azure/azure-sdk-for-android/files/7513222/build.gradle.txt)
[build.gradle-app-level.txt](https://github.com/Azure/azure-sdk-for-android/files/7513224/build.gradle-app-level.txt)

**Comment by maregood** [comment]
Hi! I have same problem when ionic build to Android with AzureChat Sdk inside my own native plugin based on your example! Any solution?

**Comment by vcolin7** [comment]
Sorry for the delayed response @Muqeeth-Pop, @maregood, I was a bit busy last week. I'm looking into this today and will let you know as soon as I have news.

**Comment by vbsteven** [comment]
I'm having similar issues. When I add `com.azure.android:azure-communication-chat:1.0.1` to implementation configuration in my app/build.gradle it errors out with the same message.

I can get around the issue by instantiating an HttpClient myself and passing it into the ChatClientBuilder:

```
val httpClient = OkHttpAsyncHttpClientBuilder().build()
                chatClient_ = ChatClientBuilder()
                    .httpClient(httpClient)
                    .endpoint("...")
                    .credential(communicationUserCredential)
                    .buildClient()
```

However, when I upgrade the communications-chat dependency to one of the beta's this workaround is not sufficient anymore. As the new beta versions have a hardcoded `HttpClientProvider.createInstance()` somewhere in the Push Notification classes, with no option to pass a custom `HttpClient` implementation.

**Comment by Muqeeth-Pop** [comment]
@vcolin7 Is there any update on this ?

**Comment by vcolin7** [comment]
Hi everyone,

I tried reproducing the issue to no avail by following [this Ionic+React tutorial](https://ionicframework.com/docs/react/your-first-app) and adding [code](https://github.com/Azure-Samples/communication-services-android-quickstarts/blob/2c711872b9beabfc0abdf90c85a53a5e349e9291/Add-chat/app/src/main/java/com/contoso/chatquickstart/MainActivity.java) from the [ACS Quickstart](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/get-started?pivots=programming-language-android) to the project's `MainActivity` class, so the moment it starts it creates a chat thread and sends a message. I also spent some time looking at @Muqeeth-Pop's files and while nothing stood out to me, I still tried as many dependency version combinations I could to make everything as close to what was shared.

Based on what @vbsteven said about using `ServiceLoader.load()` directly in their application working but not on the `azure-core-http-okhttp` package and the fact that @Muqeeth-Pop and @maregood mentioned working with React and/or Ionic, I suspect this may be related to how some third-party frameworks compartmentalize certain application components, which may lead to them being taken care of by more than one classloader.

We had [someone suggest](https://github.com/Azure/azure-sdk-for-java/pull/20760) using the same classloader that loads the `HttpClientProviders` class to load the provider for an `HttpClient` on the Java SDK and we ended up accepting their contribution. I'm don't think this will help in all cases, but I think it's a step in the right direction for some, so we [borrowed that same approach](https://github.com/Azure/azure-sdk-for-android/pull/970) for the Android SDK and made a change that will be made available during our next release in early January.

It's also worth mentioning that we had a [similar issue](https://github.com/Azure/azure-sdk-for-java/issues/25769) on the Java SDK a couple weeks ago. The way the user got around it for the time being was to pass their own `HttpClient` when using a client builder (in their case `BlobServiceClientBuilder`, here it would be `ChatClientBuilder` or `ChatClientThreadBuilder`), which aligns with what @vbsteven mentioned in their comment. That said, the problem of not allowing to set a custom `HttpClient` on ACS Chat's beta versions remains, so I will reach out to the team to update library and make this functionality available hopefully during the next release in early January as well.

**Comment by vcolin7** [comment]
If you wish to try out our code before the next releases come, you can clone our repository and build the module of your choosing using the following Gradle command:

```bash
gradle :sdk:<library-parent-folder>:<library-name>:build -x testDebugUnitTest -x testReleaseUnitTest -x lint
```

For example:

```bash
gradle :sdk:core:azure-core-http:build -x testDebugUnitTest -x testReleaseUnitTest -x lint
```

And then add it to your project.

I will post a comment here once the ACS Chat codebase is updated to allow for setting an `HttpClient` manually, which should be early next week.

**Comment by vcolin7** [comment]
@Muqeeth-Pop, @maregood So to summarize, if you are using version `1.0.0` or `1.0.1` of `azure-communication-chat` you can use the workaround of setting a custom `HttpClient` by using the `httpClient()` method in `ChatClientBuilder` and `ChatThreadClientBuilder`:

```java
ChatAsyncClient chatAsyncClient = new ChatClientBuilder()
    .httpClient(httpClient)
    .endpoint("<your-endpoint>")
    .credential(communicationUserCredential)
    .buildAsyncClient();
```

**Comment by Muqeeth-Pop** [comment]
The workaround provided by @vcolin7 suffice for now.
