### ISSUE TITLE
[BUG] Android SDK crashing when instantiating CallAgentOptions

### ISSUE THREAD

**Issue by paolo-ermit** [Azure/azure-sdk-for-android#984]
**Describe the bug**
It's not possible to create an instance of CallAgentOptions(). An exception is thrown

***Exception or Stack Trace***
>   java.lang.UnsatisfiedLinkError: No implementation found for com.azure.android.communication.calling.status com.azure.android.communication.calling.NativeLibrary.sam_call_agent_options_create(com.azure.android.communication.calling.Out) (tried Java_com_azure_android_communication_calling_NativeLibrary_sam_1call_1agent_1options_1create and Java_com_azure_android_communication_calling_NativeLibrary_sam_1call_1agent_1options_1create__Lcom_azure_android_communication_calling_Out_2)
        at com.azure.android.communication.calling.NativeLibrary.sam_call_agent_options_create(Native Method)
        at com.azure.android.communication.calling.CallAgentOptions.<init>(CallAgentOptions.java:53)

**To Reproduce**
 Create a project, add to gradle
 >  implementation 'com.azure.android:azure-communication-calling:2.0.0'

Anywhere in the code add
> CallAgentOptions callOptions = new CallAgentOptions();

***Code Snippet***
> CallAgentOptions callOptions = new CallAgentOptions();

**Expected behavior**
I would expect to be able to istantiate a CallAgentOptions object to use it as parameter in 
> CallClient.createCallAgent(....)

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Android 12
 - IDE : Android Studio
 - com.azure.android:azure-communication-calling:2.0.0

**Additional context**
Without trying to use CallAgentOptions I can perform a call without any issue.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jsaurezlee-msft** [comment]
Hi @paolo-ermit,
Is CallAgentOptions the first object your are creating? Can you try to create first a CallClient object prior creating a CallAgentOptions?

**Comment by paolo-ermit** [comment]
Hi @jsaurezlee-msft
I confirm that if I create the CallClient object before creating the CallAgentOptions object, the crash doesn't happen and the option is working correctly

**Comment by jsaurezlee-msft** [comment]
Thanks for the report @paolo-ermit. We are aware of this situation and the next release of the Android SDK will allow you to create a CallAgentOptions object before creating CallClient or CallClientOptions.

**Comment by jsaurezlee-msft** [comment]
Hi @paolo-ermit We have released version 2.1.0-beta.1 for the Android SDK with fixes for this issue.
I'm closing this for now, but feel free to reopen in case you have more comments.
