### ISSUE TITLE
[Android]: call.isMuted() always returns false in call.addOnIsMutedChangedListener() when muted remotely by host

### ISSUE THREAD

**Issue by ankiarora** [Azure/azure-sdk-for-android#995]
***Description***
When a user unmutes himself on android app and then is muted remotely from the Teams app by the host, call.addOnIsMutedChangedListener() listener is called, but inside this listener, call.isMuted() always returns false.

***Steps to reproduce the behavior:***
1. User on an android app implementing ACS SDK (2.0.0) joins the meeting
2. User is accepted to the call by a host.
3. User unmutes the call.
4. Host mutes the user from the Teams app.
5. call.addOnIsMutedChangedListener() is called, and user gets muted. But, call.isMuted() inside this listener remains false. 
6. Expected: call.isMuted() should return true.

***Code Snippet***
call.addOnIsMutedChangedListener(propertyChangedEvent -> {
            Log.i(TAG, "Call ID[" + call.getId() + "] has " + (call.isMuted() ? "" : "NOT ") + "been MUTED");
            //call.isMuted() returns false
        });

**Expected behavior**
call.addOnIsMutedChangedListener(propertyChangedEvent -> {
            Log.i(TAG, "Call ID[" + call.getId() + "] has " + (call.isMuted() ? "" : "NOT ") + "been MUTED");
            //call.isMuted() should return true once host mutes the user from Teams app
        });

**Setup (please complete the following information):**
 - OS: Android
 - IDE : Android Studio
 - Version: 2.0.0

**Additional context**
The listener was working as expected in version 1.2.1-beta.1. This issue exists in all the versions after 1.2.1-beta.1

**Comment by vcolin7** [comment]
Hi @ankiarora, thanks for letting us know about this. I will route this to the right person to look at. Just to make sure, this is in reference to the [`com.azure.android:azure-communication-calling:2.0.0`](https://search.maven.org/artifact/com.azure.android/azure-communication-calling/2.0.0/aar) package right?

**Comment by ankiarora** [comment]
@vcolin7, Thank you for replying. Yes, that's correct. 
I realized that this issue did not occur in com.azure.android:azure-communication-calling:1.2.1-beta.1. However, the recent version 2.0.0 is having this issue. Please look into this issue. 
Thank you.

**Comment by jsaurezlee-msft** [comment]
Hi @ankiarora, thanks for the report. This issue has been fixed and will be published in our next release.
